// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jooqyfsvopqopvgnykbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvb3F5ZnN2b3Bxb3B2Z255a2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDIwODQsImV4cCI6MjA1OTM3ODA4NH0.-69LxnBsArG5cZmIbHYK9Lphd0158V11-0u4LnDc3zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);